### ISSUE TITLE
Demo App: Crashes node on a bad URL

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2343]
**Describe the bug**
With a faulty URL its possible to bring down the Node JS demo app.

**To Reproduce**
1. Start Demo App
1. Go to a link like http://localhost:4000/components/idontexist/example-index.html
1. See error:
```
_http_outgoing.js:469
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:469:11)
    at Array.write (/Users/tmcconechy/Dev/master/node_modules/finalhandler/index.js:285:9)
    at listener (/Users/tmcconechy/Dev/master/node_modules/on-finished/index.js:169:15)
    at onFinish (/Users/tmcconechy/Dev/master/node_modules/on-finished/index.js:100:5)
    at callback (/Users/tmcconechy/Dev/master/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/Users/tmcconechy/Dev/master/node_modules/ee-first/index.js:93:5)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Also:
http://localhost:4000/components/idontexist/ -> Does a 404
http://localhost:4000/components/idontexist -> Shows the component index page
http://localhost:4000/components/idontexist/anything -> Has the error
http://localhost:4000/components/area/sss-test -> Shows the component sample index page

**Expected behavior**
Should be more resilient.Either :
- show a 404 like http://localhost:4000/components/idontexist bonus: Maybe show a blank page with an ids message box in the middle instead or
- just show the index components page

**Version**
- ids-enterprise: [v4.19.0]

**Comment by EdwardCoyle** [comment]
Re-opening because the demoapp is apparently no longer working on Windows due to my changes :-/
