### ISSUE TITLE
Update Node To Latest

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2667]
**Is your feature request related to a problem? Please describe.**
We are on Node 10 and npm 6. However npm 6 is no longer maintained. Should update node and npm to the latest version (LTS).

**Describe the solution you'd like**

- [ ] Update dependencies
- [ ] Test demo app
- [ ] Test Building
- [ ] Test CI

**Comment by tmcconechy** [comment]
Probably going to have to shelf this for now as innner dependencies are not yet read for node 12. Particularly this one.

```
usmvtmcconechy:master tmcconechy$ npm i fsevents --save-dev

> canvas-prebuilt@1.6.11 install /Users/tmcconechy/Dev/master/node_modules/canvas-prebuilt
> node-pre-gyp install

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/tmcconechy/Dev/master/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:214:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/tmcconechy/Dev/master/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:209:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:456:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:209:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:305:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:286:11)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/Users/tmcconechy/.nvm/versions/node/v12.9.1/bin/node" "/Users/tmcconechy/Dev/master/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/tmcconechy/Dev/master/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v12.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-darwin-x64.tar.gz
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas-prebuilt@1.6.11 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas-prebuilt@1.6.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tmcconechy/.npm/_logs/2019-09-03T14_57_15_460Z-debug.log
usmvtmcconechy:master tmcconechy$
```

Doing a lighter touch on this for now

**Comment by EdwardCoyle** [comment]
@tmcconechy Maybe we should look at this one again, per the build issues on #3748?

**Comment by tmcconechy** [comment]
yeah that was one of the driving things the default version of node is problematic. i had mean to punt this to 4.29 but i guess i didnt.

there now but that sprint is extremely ful.

**Comment by tmcconechy** [comment]
oh woops yeah i didnt mean to close this.

**Comment by jbrcna** [comment]
**QA Passed**
v4.29.0-dev
