### ISSUE TITLE
Custom build fails for component charts 

### ISSUE THREAD

**Issue by nuwanc** [infor-design/enterprise#5463]
wanted to make a custom build which includes component button and charts.
ran the following command.

npm run build -- --components=button,charts

get the below error:

`temp/index.js → dist/js/sohoxi.js...
[!] Error: 'Charts' is not exported by src\components\charts\charts.js, imported by temp\components.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
temp\components.js (4:9)
2: export { Button } from '../src/components/button/button';
3: export { ButtonSet } from '../src/components/button/button.set';
4: export { Charts } from '../src/components/charts/charts';
            ^
5:
6: // Mid ====/
Error: 'Charts' is not exported by src\components\charts\charts.js, imported by temp\components.js
    at error (C:\projects\enterprise\node_modules\rollup\dist\shared\rollup.js:151:30)
    at Module.error (C:\projects\enterprise\node_modules\rollup\dist\shared\rollup.js:10041:16)
    at Module.getVariableForExportName (C:\projects\enterprise\node_modules\rollup\dist\shared\rollup.js:10204:29)
    at Module.includeAllExports (C:\projects\enterprise\node_modules\rollup\dist\shared\rollup.js:10279:35)
    at Object.includeAllExports (C:\projects\enterprise\node_modules\rollup\dist\shared\rollup.js:10373:43)
    at NamespaceVariable.include (C:\projects\enterprise\node_modules\rollup\dist\shared\rollup.js:9627:22)
    at Module.includeVariable (C:\projects\enterprise\node_modules\rollup\dist\shared\rollup.js:10697:22)
    at Module.includeAllExports (C:\projects\enterprise\node_modules\rollup\dist\shared\rollup.js:10274:26)
    at Graph.includeStatements (C:\projects\enterprise\node_modules\rollup\dist\shared\rollup.js:20394:36)
    at Graph.build (C:\projects\enterprise\node_modules\rollup\dist\shared\rollup.js:20309:14)

ⓧ  Error: "npx rollup -c --components=button,charts" process exited with error code (1)
Args:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ids-enterprise@4.54.0-dev build: `npm run clean:dist && node ./scripts/build "--components=button,charts"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ids-enterprise@4.54.0-dev build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nchandrasoma\AppData\Roaming\npm-cache\_logs\2021-07-27T12_44_22_058Z-debug.log
`

**Comment by tmcconechy** [comment]
cc @EdwardCoyle

**Comment by tmcconechy** [comment]
@nuwanc it might be an idea to put in the names of the individual charts instead. But @EdwardCoyle will take a look

**Comment by jbrcna** [comment]
this is working as expected. moving this ticket to Done. thank you
v4.55.0-dev
http://localhost:4000/components/pie/example-donut?layout=nofrills
