### ISSUE TITLE
Date field crashing in monthview.js in 4.71.x

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#7086]
**Describe the bug**
When clicking the month view chooser in a date field an exception is thrown

```
Uncaught TypeError: s.disable.minDate.replace is not a function
    at MonthView.isDateDisabled (node_modules\ids-enterprise\dist\js\sohoxi.js:51007:1)
    at MonthView.setDisabled (node_modules\ids-enterprise\dist\js\sohoxi.js:50957:1)
    at HTMLTableCellElement.<anonymous> (node_modules\ids-enterprise\dist\js\sohoxi.js:50396:1)
    at Function.each (node_modules\jquery\dist\jquery.js:381:1)
    at jQuery.fn.init.each (node_modules\jquery\dist\jquery.js:203:1)
    at MonthView.showMonth (node_modules\ids-enterprise\dist\js\sohoxi.js:50386:1)
    at MonthView.build (node_modules\ids-enterprise\dist\js\sohoxi.js:50046:1)
    at Array.<anonymous> (node_modules\ids-enterprise\dist\js\sohoxi.js:49975:1)
    at fire (node_modules\jquery\dist\jquery.js:3496:1)
    at Object.add [as done] (node_modules\jquery\dist\jquery.js:3555:1)
```

**To Reproduce**
Not completely sure, perhaps is just that we are passing in a Date object for s.disable.minDate and s.disable.maxDate and this code seems to be expecting a string. 

https://github.com/infor-design/enterprise/blob/main/src/components/monthview/monthview.js#L1319

This seems to be new to 4.71.x. In 4.70.x it seems to work.

https://github.com/infor-design/enterprise/blame/95b7eea8ac4b5da414dd72da3151559e4a665c5f/src/components/monthview/monthview.js#L1317

**Version**
- ids-enterprise: 4.71.0-beta.1

**Screenshots**
![image](https://user-images.githubusercontent.com/4737815/211624126-b7ecdbfd-a493-4ce6-bbac-5a4992a73ccd.png)

**Comment by tmcconechy** [comment]
@ericangeles will also have to check this out as well

**Comment by jbrcna** [comment]
QA Passed.
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/56722184/212820346-b8bac905-df43-4cb4-876a-46ef276e0ad4.png">
