### ISSUE TITLE
BusyIndicator: Fails when updated called with no arguments.

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise#8257]
**Describe the bug**

After upgrading to id-enterprise-ng v17.1.1 / enterprise v4.90.0 the busy indicator is throwing errors when being updated.

```
TypeError: Cannot read properties of undefined (reading 'text')
    at BusyIndicator.updated (http://ukfantharper01.infor.com:40012/sunsystems/deployment/scripts.js:60509:20)
    at HTMLDivElement.<anonymous> (http://ukfantharper01.infor.com:40012/sunsystems/deployment/scripts.js:60570:16)
    at HTMLDivElement.dispatch (http://ukfantharper01.infor.com:40012/sunsystems/deployment/scripts.js:5466:27)
    at elemData.handle (http://ukfantharper01.infor.com:40012/sunsystems/deployment/scripts.js:5270:28)
    at Object.trigger (http://ukfantharper01.infor.com:40012/sunsystems/deployment/scripts.js:8801:12)
    at HTMLInputElement.<anonymous> (http://ukfantharper01.infor.com:40012/sunsystems/deployment/scripts.js:8879:17)
    at Function.each (http://ukfantharper01.infor.com:40012/sunsystems/deployment/scripts.js:385:19)
    at jQuery.fn.init.each (http://ukfantharper01.infor.com:40012/sunsystems/deployment/scripts.js:207:17)
    at jQuery.fn.init.trigger (http://ukfantharper01.infor.com:40012/sunsystems/deployment/scripts.js:8878:15)
    at HTMLInputElement.<anonymous> (http://ukfantharper01.infor.com:40012/sunsystems/deployment/scripts.js:125593:15)
```

The problem looks to be caused by code added to escape the text on the settings object:

```javascript
updated(settings) {
  if (settings.text) {
    settings.text = xssUtils.unescapeHTML(settings.text);
  }
  this.settings = utils.mergeSettings(this.element, settings, this.settings);
  return this.setup();
},
```

**To Reproduce**

Create a `busy indicator` and call `updated`.

```javascript
if (this.busyindicator && this.updateBusyIndicator) {
      // call outside the angular zone so change detection isn't triggered by the soho component.
      this.ngZone.runOutsideAngular(() => {
        this.updateBusyIndicator = false;
        this.busyindicator?.updated();
      });
    }
```

**Expected behavior**

The updated method should handle no arguments - which is used in the ids-enterprise-ng components.

**Version**

- ids-enterprise-ng: v17.1.1
- ids-enterprise: v4.90.0

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor SunSystems
 - Device: Windows
 - OS Version: Windows 11
 - Browser Name: Chrome and Edge
 - Browser Version:  120.0.2210.61

**Additional context**

**Comment by ericangeles** [comment]
@tjamesallen15, could you take a look at this? It seems that this issue is related to this PR: https://github.com/infor-design/enterprise/pull/8210.
