### ISSUE TITLE
DataGrid-ToolbarFlex: Uncaught TypeError: args2.attr is not a function

### ISSUE THREAD

**Issue by adamzhang1932** [infor-design/enterprise#8564]
**Describe the bug**
```
Uncaught TypeError: args2.attr is not a function
    at HTMLDivElement.selectHandler (datagrid.js:7956:70)
    at HTMLDivElement.dispatch (jquery-3.7.1.js:5145:27)
    at elemData.handle (jquery-3.7.1.js:4949:28)
    at Object.trigger (jquery-3.7.1.js:8629:12)
    at HTMLButtonElement.<anonymous> (jquery-3.7.1.js:8707:17)
    at Function.each (jquery-3.7.1.js:383:19)
    at jQuery.fn.init.each (jquery-3.7.1.js:205:17)
    at jQuery.fn.init.trigger (jquery-3.7.1.js:8706:15)
    at ToolbarFlexItem.triggerSelectedEvent (toolbar-flex.item.js:245:21)
    at set selected (toolbar-flex.item.js:189:12)
    at HTMLButtonElement.<anonymous> (toolbar-flex.item.js:464:22)
    at HTMLButtonElement.dispatch (jquery-3.7.1.js:5145:27)
    at elemData.handle (jquery-3.7.1.js:4949:28)
    at Object.trigger (jquery-3.7.1.js:8629:12)
    at HTMLButtonElement.<anonymous> (jquery-3.7.1.js:8707:17)
    at Function.each (jquery-3.7.1.js:383:19)
    at jQuery.fn.init.each (jquery-3.7.1.js:205:17)
    at jQuery.fn.init.trigger (jquery-3.7.1.js:8706:15)
    at ToolbarFlexItem.triggerSelectedEvent (toolbar-flex.item.js:245:21)
    at set selected (toolbar-flex.item.js:189:12)
    at ToolbarFlex.select (toolbar-flex.js:968:22)
    at ToolbarFlex.handleItemClick (toolbar-flex.js:696:10)
    at ToolbarFlex.handleClick (toolbar-flex.js:681:12)
```

**To Reproduce**

1. Npm run start the IDS 4.93.0 locally.
2. Visit the link below
http://localhost:4000/components/datagrid/example-custom-toolbar-flex.html
3. Click the  '...' icon twice.
4. You can see the error on console.

**Expected behavior**

**Version**

- ids-enterprise: v4.93.0 (And this problem might occur very earlier.)

**Screenshots**
Download this video and see how to reproduce this issue.
[DataGrid-ToolbarFlex-Error.zip](https://github.com/infor-design/enterprise/files/14719140/DataGrid-ToolbarFlex-Error.zip)

**Platform**
 - Infor Application/Team Name: Infor SunSystems
 - Device: 
 - OS Version: 
 - Browser Name: Chrome
 - Browser Version: 123.0.6312.58 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@ericangeles I think we should look at this, for this sprint

**Comment by AAlviar** [comment]
also related to #8430
